name: Test CI

on:
  push:
    branches: [staging]
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "docs/**"
  pull_request:
    branches: [staging]
    paths-ignore:
      - ".gitignore"
      - "README.md"
      - "docs/**"
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
          pip install .

      - name: Lint with pylint
        run: pylint --rcfile=.pylintrc ./src/qclight

      - name: Test with pytest
        run: pytest
